// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package embridge;

import java.util.Map;

import embridge.Comment;
import embridge.Post;
import embridge.PostReaction;

/************************************************************/
/**
 * 
 */
public class Account {
	/**
	 * 
	 */
	
	private String userName;
	/**
	 * 
	 */
	private String password;
	/**
	 * 
	 */
	private String fullName;
	/**
	 * 
	 */
	private String email;
	
	ActivityController activityController;
	
	public Account(String userName, String password, String fullName, String email, ActivityController activityController) {
		this.userName = userName;
		this.password = password;
		this.fullName = fullName;
		this.email = email;
		this.activityController = activityController;
	}
	/**
	 * 
	 */
	public Post[] posts;
	/**
	 * 
	 */
	public Map<Post,Comment> comments;
	/**
	 * 
	 */
	public Map<Post,PostReaction> postreactions;
	
	public String getUserName() {
		return userName;
	}
	public void setUserName(String userName) {
		this.userName = userName;
	}
	public String getPassword() {
		return password;
	}
	public void setPassword(String password) {
		this.password = password;
	}
	public String getFullName() {
		return fullName;
	}
	public void setFullName(String fullName) {
		this.fullName = fullName;
	}
	public String getEmail() {
		return email;
	}
	public void setEmail(String email) {
		this.email = email;
	}
};
