// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package embridge;

import java.util.ArrayList;
import java.util.Scanner;

import embridge.Account;

/************************************************************/
/**
 * 
 */
public class AccountDao {
	/**
	 * 
	 * @param a 
	 */
	ArrayList<Account> accounts;
	public AccountDao(){
		
		accounts = new ArrayList<Account>();
		}
	
	public boolean addAccount(Account a) {
	try                {
		
		accounts.add(a);
		System.out.println(a.getUserName() + " account has been added to the platform");
 	    return true;
	                   }
	
	catch(Exception e) {
		System.out.println("Error when adding account");
		return false;
	                  }
	}

	/**
	 * 
	 */
	public void getAllAccounts() {
     for (Account account: accounts) {
    	 String userName = account.getUserName();
    	 System.out.println(userName + "\n");
     }
	}

	/**
	 * 
	 * @param a 
	 */
	public void updateAccount(Account a) {
		Scanner reader = new Scanner(System.in);
    
		System.out.println("Enter 1 for password change " + "\n" 
				          +"Enter 2 for username change " + "\n"
				          +"Enter 3 for email change " + "\n");
		int command = reader.nextInt();
		switch(command) {
		  
		   case 1:
			   Scanner password_scanner = new Scanner(System.in);
			   System.out.println("Enter old password: ");
			   String old_password = password_scanner.nextLine();
			 
			   if (a.getPassword() == old_password) {
				   System.out.println("Enter new password: ");
				   String new_passowrd =  password_scanner.next();
				   a.setPassword(new_passowrd);
				   System.out.println("Password successfully changed");	   
				   
			                                       }
			   else {
				   System.out.println("Wrong Password");
				  
			        }
			   
		       break;
			   
		   case 2:
			   Scanner username_scanner = new Scanner(System.in);
			   System.out.println("Enter new username: ");
			   String new_username = username_scanner.nextLine();
			   a.setUserName(new_username);
               System.out.println("Username changed successfully: " + a.getUserName());
			   
               break;
		   
		   case 3:
			   Scanner email_scanner = new Scanner(System.in);
			   System.out.println("Enter new email: ");
			   String new_email = email_scanner.nextLine();
			   a.setEmail(new_email);
               System.out.println("Email changed successfully: "+ a.getEmail());
               
               break;
            
           default:
        	 
        	   System.out.println("Enter a number from the list to update your account");
               
		 }
	}

	/**
	 * 
	 * @param a 
	 */
	public void deleteAccount(Account a) {
		
	}
};
