// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package embridge;

import embridge.Account;
import embridge.AuthenticationController;
import embridge.CommentBuilder;
import embridge.CommentFactory;
import embridge.Group;
import embridge.MessageBuilder;
import embridge.Post;
import embridge.PostBuilder;
import embridge.PostFactory;
import embridge.PostReactionHandler;

/************************************************************/
/**
 * 
 */
public class ActivityController {
	/**
	 * 
	 * @param p 
	 */
	public Post createPost(String content, String postType) {
		PostBuilder postBuilder = new PostBuilder();
		
		
		if (content == "Text") {
			Post createdPost = postBuilder.createText(postType);
			return createdPost;
		}
		if (content == "Image") {
			Post createdPost = postBuilder.createImage(postType);
			return createdPost;
		
		}
		if (content == "Video") {
			Post createdPost = postBuilder.createVideo(postType);
			return createdPost;
			
		}		if (content == "TextImage") {
			Post createdPost = postBuilder.createTextImage(postType);
			return createdPost;
		
		}		if (content == "VideoImage") {
			Post createdPost = postBuilder.createImageVideo(postType);
			return createdPost;
		
		}		if (content == "TextVideo") {
			Post createdPost = postBuilder.createTextVideo(postType);
			return createdPost;
		}
			if (content == "TextImageVideo") {
				Post createdPost = postBuilder.createTextImageVideo(postType);
				return createdPost;
			
			}
		
		
		return null;
		
	}

	/**
	 * 
	 * @param p 
	 * @param g 
	 */
	public void createPostGroup(Post p, Group g) {
	}

	/**
	 * 
	 * @param a 
	 */
	public void authenticate(Account a) {
	}

	/**
	 * 
	 * @param p 
	 */


	/**
	 * 
	 * @param m 
	 */
	public void reactToPost(Post post, String command) {
		if (command == "Like") {
			LikePost likePost = new LikePost(post);
			PostReactionHandler postReactionHandler = new PostReactionHandler();
			postReactionHandler.receiveReaction(likePost);
			postReactionHandler.addReaction();
			
		}
		if (command == "DisLike") {
			DislikePost dislikePost = new DislikePost(post);
			PostReactionHandler postReactionHandler = new PostReactionHandler();
			postReactionHandler.receiveReaction(dislikePost);
			postReactionHandler.addReaction();
			
		}
		
	}
	
	/**
	 * 
	 * @param m 
	 */
	public void sendMessage(Message m) {
	}

	/**
	 * 
	 */
	public void createGroup() {
	}

	/**
	 * 
	 * @param a 
	 */
	public void editProfile(Account a) {
	}

	/**
	 * 
	 * @param a 
	 */
	public void changePassword(Account a) {
	}
};
