// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package embridge;

import embridge.Account;
import embridge.AuthenticationController;
import embridge.CommentBuilder;
import embridge.CommentFactory;
import embridge.Group;
import embridge.MessageBuilder;
import embridge.Post;
import embridge.PostBuilder;
import embridge.PostFactory;
import embridge.PostReactionHandler;

/************************************************************/
/**
 * 
 */
public class ActivityController {
	/**
	 * 
	 * @param p 
	 */
	public void createPost(String content, String postType) {
		PostBuilder postBuilder = new PostBuilder();
		
		
		if (content == "Text") {
			postBuilder.createText(postType);
		}
		if (content == "Image") {
			postBuilder.createImage(postType);
		
		}
		if (content == "Video") {
			postBuilder.createVideo(postType);
		
		}		if (content == "TextImage") {
			postBuilder.createTextImage(postType);
		
		}		if (content == "VideoImage") {
			postBuilder.createImageVideo(postType);
		
		}		if (content == "TextVideo") {
			postBuilder.createTextVideo(postType);
		}
			if (content == "TextImageVideo") {
				postBuilder.createTextImageVideo(postType);
			
			}
		
		
		
		
	}

	/**
	 * 
	 * @param p 
	 * @param g 
	 */
	public void createPostGroup(Post p, Group g) {
	}

	/**
	 * 
	 * @param a 
	 */
	public void authenticate(Account a) {
	}

	/**
	 * 
	 * @param p 
	 */
	public void reactToPost(Post p) {
	}

	/**
	 * 
	 * @param m 
	 */
	public void sendMessage(Message m) {
	}

	/**
	 * 
	 */
	public void createGroup() {
	}

	/**
	 * 
	 * @param a 
	 */
	public void editProfile(Account a) {
	}

	/**
	 * 
	 * @param a 
	 */
	public void changePassword(Account a) {
	}
};
