// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package embridge;

import embridge.Account;

/************************************************************/
/**
 * 
 */
public class AuthenticationController {
	/**
	 * 
	 * @param a 
	 */
	public void validateLogin(Account a) {
	}
};
