// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package embridge;

import java.sql.Date;

import embridge.ContentType;

/************************************************************/
/**
 * 
 */
public interface Comment {
	/**
	 * 
	 */


	/**
	 * 
	 * @param c 
	 */
	public void addContent(ContentType c);

	/**
	 * 
	 */
	public void showContent();
};
