// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package embridge;

import embridge.Comment;

/************************************************************/
/**
 * 
 */
public class CommentBuilder {
	/**
	 * 
	 */
	public void createText() {
	}

	/**
	 * 
	 */
	public void createImage() {
	}

	/**
	 * 
	 */
	public void createVideo() {
	}
};
