// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package embridge;

import embridge.Comment;

/************************************************************/
/**
 * 
 */
public class CommentFactory {
	/**
	 * 
	 */
	public void getComment() {
	}
};
