// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package embridge;

import embridge.Comment;

/************************************************************/
/**
 * 
 */
public class CommentDao {
	/**
	 * 
	 */
	public void getAllComments() {
	}

	/**
	 * 
	 * @param c 
	 */
	public void addComment(Comment c) {
	}

	/**
	 * 
	 * @param c 
	 */
	public void deleteComment(Comment c) {
	}
};
