// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package embridge;

import embridge.Comment;
import embridge.PostReaction;

/************************************************************/
/**
 * 
 */
public class CommentOnPost implements PostReaction {

	@Override
	public void reactToPost(Post p) {
		// TODO Auto-generated method stub
		
	}
	
	
};
