// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package embridge;

/************************************************************/
/**
 * 
 */
public interface ContentType {
	/**
	 * 
	 */
	public String nameContentType();
	public String createContent();
}
