// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package embridge;

import embridge.PostReaction;

/************************************************************/
/**
 * 
 */
public class DislikePost implements PostReaction {
	 
	private Post post;

	   public DislikePost(Post post){
	      this.post = post;
	   }

	  
	@Override
	public void reactToPost() {
		// TODO Auto-generated method stub
		 post.setDislikeCount();
		
	}
};
