// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package embridge;

import java.util.Date;

import embridge.Account;
import embridge.GroupRequest;

/************************************************************/
/**
 * 
 */
public class Group {
	/**
	 * 
	 */
	private int group_id;
	/**
	 * 
	 */
	private String group_name;
	/**
	 * 
	 */
	private String description;
	/**
	 * 
	 */
	private Date creationDate;

	/**
	 * 
	 * @param a 
	 */
	public void addAccount(Account a) {
	}

	/**
	 * 
	 * @param a 
	 */
	public void removeAccount(Account a) {
	}

	/**
	 * 
	 */
	public void removeAll() {
	}

	/**
	 * 
	 * @param a 
	 */
	public void addAdmin(Account a) {
	}

	/**
	 * 
	 * @param a 
	 */
	public void removeAdmin(Account a) {
	}

	/**
	 * 
	 * @param gr 
	 */
	public void acceptRequest(GroupRequest gr) {
	}

	/**
	 * 
	 * @param gr 
	 */
	public void declineRequest(GroupRequest gr) {
	}
};
