// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package embridge;

import embridge.Group;

/************************************************************/
/**
 * 
 */
public class GroupDao {
	/**
	 * 
	 */
	public void getAllGroups() {
	}

	/**
	 * 
	 * @param g 
	 */
	public void addGroup(Group g) {
	}

	/**
	 * 
	 * @param g 
	 */
	public void deleteGroup(Group g) {
	}

	/**
	 * 
	 * @param g 
	 */
	public void updateGroup(Group g) {
	}
};
