// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package embridge;

import java.sql.Date;

/************************************************************/
/**
 * 
 */
public class GroupRequest {
	/**
	 * 
	 */
	private int request_id;
	/**
	 * 
	 */
	private Date issueDate;
};
