// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package embridge;

import embridge.PostReaction;

/************************************************************/
/**
 * 
 */
public class LikePost implements PostReaction {
     
	 private Post post;

	   public LikePost(Post post){
	      this.post = post;
	   }

	   public void reactToPost() {
	      post.setLikeCount();
	   }
 
}
