// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package embridge;

import embridge.PostReaction;

/************************************************************/
/**
 * 
 */
public class LikePost implements PostReaction {

	@Override
	public void reactToPost(Post p) {
		// TODO Auto-generated method stub
		
	}
};
