// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package embridge;

import java.sql.Date;
import java.util.ArrayList;
import java.util.List;

/************************************************************/
/**
 * 
 */
public class Message {
	/**
	 * 
	 */
	private int message_id;
	/**
	 * 
	 */
	private Date issueDate;
	/**
	 * 
	 */
	private List<ContentType> content;
	/**
	 * 
	 */
	public void addContent(ContentType c) {
		
	}
	/**
	 * 
	 */
	public List<ContentType> showContent(){
		List<ContentType> content = new ArrayList<ContentType>();
		return content;
	}
	
};
