// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package embridge;

import embridge.Message;

/************************************************************/
/**
 * 
 */
public class MessageDao {
	/**
	 * 
	 */
	public void getAllMessages() {
	}

	/**
	 * 
	 * @param m 
	 */
	public void addMessage(Message m) {
	}

	/**
	 * 
	 * @param m 
	 */
	public void deleteMessage(Message m) {
	}
};
