// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package embridge;

import java.util.Scanner;

import embridge.*;
/************************************************************/
/**
 * 
 */
public class PostBuilder {
	/**
	 * 
	 */
	PostFactory postFactory = new PostFactory();
	Scanner scanner = new Scanner(System.in);
	public void createText(String postType) {
		System.out.println("Enter your text content: ");
		String content = scanner.nextLine();
	    Post textPost = postFactory.getPost(postType);
	    textPost.addContent(new Text(content));
	    textPost.showContent();
	    textPost.postType();
	}

	/**
	 * 
	 */
	public void createImage(String postType) {
		System.out.println("Enter your image url: ");
		String image_url = scanner.nextLine();
		Post imagePost = postFactory.getPost(postType);
	    imagePost.addContent(new Image(image_url));
	    imagePost.showContent();;
	}

	/**
	 * 
	 */
	public void createVideo(String postType) {
		System.out.println("Enter your video url: ");
		String video_url = scanner.nextLine();
		Post videoPost = postFactory.getPost(postType);
		videoPost.addContent(new Video(video_url));
		videoPost.showContent();
		videoPost.postType();
	}
	/**
	 * 
	 */
	public void createTextImage(String postType) {
		System.out.println("Enter your text content: ");
		String content = scanner.nextLine();
		System.out.println("Enter your image url: ");
		String image_url = scanner.nextLine();
		Post textImagePost = postFactory.getPost(postType);
		textImagePost.addContent(new Text(content));
		textImagePost.addContent(new Image(image_url));
        textImagePost.showContent();
        textImagePost.postType();
		
	}

	/**
	 * 
	 */
	public void createImageVideo(String postType) {
		System.out.println("Enter your image url: ");
		String image_url = scanner.nextLine();
		System.out.println("Enter your video url: ");
		String video_url = scanner.nextLine();
		Post imageVideoPost = postFactory.getPost(postType);
		imageVideoPost.addContent(new Image(image_url));
		imageVideoPost.addContent(new Video(video_url));
		imageVideoPost.showContent();
		imageVideoPost.postType();
	}

	/**
	 * 
	 */
	public void createTextVideo(String postType) {
		System.out.println("Enter your text content: ");
		String content = scanner.nextLine();
		System.out.println("Enter your video url: ");
		String video_url = scanner.nextLine();
		Post textVideoPost = postFactory.getPost(postType);
		textVideoPost.addContent(new Text(content));
		textVideoPost.addContent(new Video(video_url));
	    textVideoPost.showContent();
	    textVideoPost.postType();
	}
	/**
	 * 
	 */
	
	public void createTextImageVideo(String postType) {
		System.out.println("Enter your text content: ");
		String content = scanner.nextLine();
		System.out.println("Enter your image url: ");
		String image_url = scanner.nextLine();
		System.out.println("Enter your video url: ");
		String video_url= scanner.nextLine();
		Post textImageVideoPost = postFactory.getPost(postType);
		textImageVideoPost.addContent(new Text(content));
		textImageVideoPost.addContent(new Image(image_url));
		textImageVideoPost.addContent(new Video(video_url));
		textImageVideoPost.showContent();
		textImageVideoPost.postType();
		
	}
	
	/**
	 * 
	 */
	
	
}
