// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package embridge;

import embridge.Post;

/************************************************************/
/**
 * 
 */
public class PostDao {
	/**
	 * 
	 */
	public void getAllPosts() {
	}

	/**
	 * 
	 * @param p 
	 */
	public void updatePost(Post p) {
	}

	/**
	 * 
	 * @param p 
	 */
	public void addPost(Post p) {
	}

	/**
	 * 
	 * @param p 
	 */
	public void deletePost(Post p) {
	}
};
