// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package embridge;

import embridge.Post;
import embridge.PostReaction;

/************************************************************/
/**
 * 
 */
public class PostReactionHandler {
	/**
	 * 
	 * @param p 
	 * @param pr 
	 */
	public void receiveReaction(Post p, PostReaction pr) {
	}

	/**
	 * 
	 * @param p 
	 * @param pr 
	 */
	public void addReaction(Post p, PostReaction pr) {
	}
};
