// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package embridge;

import java.util.ArrayList;
import java.util.List;

import embridge.Post;
import embridge.PostReaction;

/************************************************************/
/**
 * 
 */
public class PostReactionHandler {
	/**
	 * 
	 * @param p 
	 * @param pr 
	 */
	 private List<PostReaction> reactionList = new ArrayList<PostReaction>(); 

	  

	   
	public void receiveReaction(PostReaction pr) {
		
		reactionList.add(pr);
	}

	/**
	 * 
	 * @param p 
	 * @param pr 
	 */
	public void addReaction() {
		
		 for (PostReaction postReaction : reactionList) {
	         postReaction.reactToPost();
	      }
	      reactionList.clear();
	}
};
