// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package embridge;

import embridge.Post;

/************************************************************/
/**
 * 
 */
public interface PostReaction {
	/**
	 * 
	 */
	/**
	 * 
	 * @param p 
	 */
	public void reactToPost();
};
