// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package embridge;

import embridge.Comment;

/************************************************************/
/**
 * 
 */
public class RegularComment implements Comment {

	@Override
	public void addContent(ContentType c) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public void showContent() {
		// TODO Auto-generated method stub
		
	}

};
