// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package embridge;

import embridge.ContentType;
import embridge.Post;

/************************************************************/
/**
 * 
 */
public class TaggedPost extends Post {

	public String postType() {
		
		return "This is a tagged post";
	}
}
