// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package embridge;

import embridge.ContentType;

/************************************************************/
/**
 * 
 */
public class Video implements ContentType {

   	
	private String video_url;
	
	public String nameContentType() {
		
		return "Video";
	}
	public Video(String video_url) {
		
		this.video_url = video_url;
	}
	@Override
	public String createContent() {
		// TODO Auto-generated method stub
		return video_url;
		
	}
};
